// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Xote__Id from "./Xote__Id.res.mjs";
import * as Xote__Core from "./Xote__Core.res.mjs";

function make(v) {
  var id = Xote__Id.make();
  Xote__Core.ensureSignalBucket(id);
  return {
          id: id,
          value: {
            contents: v
          },
          version: {
            contents: 0
          }
        };
}

function get(s) {
  var obsId = Xote__Core.currentObserverId.contents;
  if (obsId !== undefined) {
    Xote__Core.addDep(obsId, s.id);
  }
  return s.value.contents;
}

function peek(s) {
  return s.value.contents;
}

function set(s, v) {
  if (Caml_obj.equal(v, s.value.contents)) {
    return ;
  } else {
    s.value.contents = v;
    s.version.contents = s.version.contents + 1 | 0;
    return Xote__Core.notify(s.id);
  }
}

function update(s, f) {
  set(s, f(s.value.contents));
}

var IntSet;

var IntMap;

var Observer;

var Id;

var Core;

export {
  IntSet ,
  IntMap ,
  Observer ,
  Id ,
  Core ,
  make ,
  get ,
  peek ,
  set ,
  update ,
}
/* No side effect */
