// Generated by ReScript, PLEASE EDIT WITH CARE


var next = {
  contents: 0
};

function make() {
  next.contents = next.contents + 1 | 0;
  return next.contents;
}

export {
  next ,
  make ,
}
/* No side effect */
