// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Xote__Id from "./Xote__Id.res.mjs";
import * as Xote__Core from "./Xote__Core.res.mjs";
import * as Belt_MapInt from "rescript/lib/es6/belt_MapInt.js";
import * as Xote__Signal from "./Xote__Signal.res.mjs";

function make(calc) {
  var s = Xote__Signal.make();
  var initialized = {
    contents: false
  };
  var id = Xote__Id.make();
  var recompute = function () {
    var next = calc();
    if (initialized.contents === false) {
      initialized.contents = true;
      return Xote__Signal.set(s, next);
    } else {
      return Xote__Signal.set(s, next);
    }
  };
  var o = {
    id: id,
    kind: {
      NAME: "Computed",
      VAL: s.id
    },
    run: recompute,
    deps: undefined
  };
  Xote__Core.observers.contents = Belt_MapInt.set(Xote__Core.observers.contents, id, o);
  Xote__Core.clearDeps(o);
  Xote__Core.currentObserverId.contents = id;
  o.run();
  Xote__Core.currentObserverId.contents = undefined;
  return s;
}

var IntSet;

var IntMap;

var Signal;

var Core;

var Observer;

var Id;

export {
  IntSet ,
  IntMap ,
  Signal ,
  Core ,
  Observer ,
  Id ,
  make ,
}
/* No side effect */
