// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Xote__Id from "./Xote__Id.res.mjs";
import * as Xote__Core from "./Xote__Core.res.mjs";
import * as Belt_MapInt from "rescript/lib/es6/belt_MapInt.js";

function run(fn) {
  var id = Xote__Id.make();
  var o = {
    id: id,
    kind: "Effect",
    run: (function () {
        fn();
      }),
    deps: undefined
  };
  Xote__Core.observers.contents = Belt_MapInt.set(Xote__Core.observers.contents, id, o);
  Xote__Core.clearDeps(o);
  Xote__Core.currentObserverId.contents = id;
  o.run();
  Xote__Core.currentObserverId.contents = undefined;
  var dispose = function () {
    var o = Belt_MapInt.get(Xote__Core.observers.contents, id);
    if (o !== undefined) {
      Xote__Core.clearDeps(o);
      Xote__Core.observers.contents = Belt_MapInt.remove(Xote__Core.observers.contents, id);
      return ;
    }
    
  };
  return {
          dispose: dispose
        };
}

var IntSet;

var IntMap;

var Id;

var Observer;

var Signal;

var Core;

export {
  IntSet ,
  IntMap ,
  Id ,
  Observer ,
  Signal ,
  Core ,
  run ,
}
/* No side effect */
