// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Xote__Core from "./Xote__Core.res.mjs";
import * as Xote__Effect from "./Xote__Effect.res.mjs";
import * as Xote__Signal from "./Xote__Signal.res.mjs";
import * as Xote__Computed from "./Xote__Computed.res.mjs";

var count = Xote__Signal.make(0);

var $$double = Xote__Computed.make(function () {
      return (Xote__Signal.get(count) << 1);
    });

var eff = Xote__Effect.run(function () {
      console.log("count:", Xote__Signal.get(count));
      console.log("double:", Xote__Signal.get($$double));
    });

Xote__Signal.set(count, 1);

Xote__Signal.update(count, (function (n) {
        return n + 1 | 0;
      }));

Xote__Core.untrack(function () {
      console.log("peek double (no track)", Xote__Signal.peek($$double));
    });

Xote__Core.batch(function () {
      Xote__Signal.set(count, 10);
      Xote__Signal.set(count, 11);
    });

var Computed;

var Core;

var Effect;

var Signal;

export {
  Computed ,
  Core ,
  Effect ,
  Signal ,
  count ,
  $$double ,
  eff ,
}
/* count Not a pure module */
